security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        from_db:
            entity: {class: UserBundle:User, property: username}

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN]
        ROLE_ADMIN: ROLE_AMIN
        ROLE_TEACHER: ROLE_TEACHER
        ROLE_STUDENT: ROLE_STUDENT



    firewalls:
        secured:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /hello
            logout:
                path: /logout
                target: /
            anonymous: ~



