<?php

namespace ManagementBundle\Repository;

/**
 * StudentEvaltuationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentEvaltuationsRepository extends \Doctrine\ORM\EntityRepository
{
}
