subject_index:
    path:     /
    defaults: { _controller: "EschoolBundle:Subject:index" }
    methods:  GET

subject_show:
    path:     /{id}/show
    defaults: { _controller: "EschoolBundle:Subject:show" }
    methods:  GET

subject_new:
    path:     /new
    defaults: { _controller: "EschoolBundle:Subject:new" }
    methods:  [GET, POST]

subject_edit:
    path:     /{id}/edit
    defaults: { _controller: "EschoolBundle:Subject:edit" }
    methods:  [GET, POST]

subject_delete:
    path:     /{id}/delete
    defaults: { _controller: "EschoolBundle:Subject:delete" }
    methods:  DELETE
